import { FullReport, AuthorStats, GrowthPoint, LanguageEntry, CommitPattern } from '../types';

// ---------------------------------------------------------------------------
// CSS + page shell
// ---------------------------------------------------------------------------

function htmlShell(title: string, body: string, scripts: string): string {
  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8"/>
<meta name="viewport" content="width=device-width,initial-scale=1"/>
<title>${escHtml(title)}</title>
<script src="https://cdn.jsdelivr.net/npm/chart.js@4/dist/chart.umd.min.js"></script>
<style>
*{box-sizing:border-box;margin:0;padding:0}
body{background:#0d1117;color:#c9d1d9;font-family:'Segoe UI',system-ui,sans-serif;line-height:1.6;padding:2rem}
h1{color:#58a6ff;font-size:2rem;margin-bottom:.25rem}
h2{color:#79c0ff;font-size:1.25rem;margin:2rem 0 1rem;border-bottom:1px solid #30363d;padding-bottom:.5rem}
.meta{color:#8b949e;font-size:.875rem;margin-bottom:2rem}
.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(280px,1fr));gap:1.5rem;margin-bottom:2rem}
.card{background:#161b22;border:1px solid #30363d;border-radius:8px;padding:1.25rem}
.card h3{color:#58a6ff;font-size:1rem;margin-bottom:.75rem}
.stat{font-size:2rem;font-weight:700;color:#f0f6fc}
.stat-label{color:#8b949e;font-size:.8rem}
table{width:100%;border-collapse:collapse;font-size:.875rem}
th{background:#21262d;color:#8b949e;text-align:left;padding:.5rem .75rem;border-bottom:1px solid #30363d}
td{padding:.4rem .75rem;border-bottom:1px solid #21262d}
tr:last-child td{border-bottom:none}
.add{color:#3fb950}.del{color:#f85149}.num{text-align:right}
.bar-cell{background:#161b22;border-radius:4px;overflow:hidden;height:8px;min-width:60px}
.bar-fill{height:100%;background:linear-gradient(90deg,#238636,#3fb950)}
.bar-fill.warn{background:linear-gradient(90deg,#9e6a03,#e3b341)}
.bar-fill.danger{background:linear-gradient(90deg,#8b1a1a,#f85149)}
canvas{max-width:100%;margin-top:.5rem}
.chart-wrap{background:#161b22;border:1px solid #30363d;border-radius:8px;padding:1.25rem;margin-bottom:1.5rem}
footer{color:#8b949e;font-size:.75rem;margin-top:3rem;text-align:center;border-top:1px solid #30363d;padding-top:1rem}
</style>
</head>
<body>
${body}
<footer>Generated by gitstats · ${new Date().toISOString()}</footer>
<script>
${scripts}
</script>
</body>
</html>`;
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function escHtml(s: string): string {
  return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
}

function summaryCards(report: FullReport): string {
  const totalCommits = report.authors.reduce((s, a) => s + a.commits, 0);
  const totalAdded   = report.authors.reduce((s, a) => s + a.linesAdded, 0);
  const totalRemoved = report.authors.reduce((s, a) => s + a.linesRemoved, 0);

  const card = (stat: string, label: string, cls = '') =>
    `<div class="card"><div class="stat ${cls}">${stat}</div><div class="stat-label">${label}</div></div>`;

  return `<div class="grid">
${card(totalCommits.toLocaleString(), 'Total Commits')}
${card(report.authors.length.toString(), 'Contributors')}
${card('+' + totalAdded.toLocaleString(), 'Lines Added', 'add')}
${card('-' + totalRemoved.toLocaleString(), 'Lines Removed', 'del')}
</div>`;
}

// ---------------------------------------------------------------------------
// Section builders
// ---------------------------------------------------------------------------

function authorsSection(authors: AuthorStats[]): string {
  const rows = authors.slice(0, 20).map(a => {
    const pct = authors[0]?.commits > 0 ? (a.commits / authors[0].commits) * 100 : 0;
    return `<tr>
<td>${escHtml(a.name)}</td>
<td class="num">${a.commits}</td>
<td class="num add">+${a.linesAdded.toLocaleString()}</td>
<td class="num del">-${a.linesRemoved.toLocaleString()}</td>
<td class="num">${a.activeDays}</td>
<td><div class="bar-cell"><div class="bar-fill" style="width:${pct.toFixed(1)}%"></div></div></td>
</tr>`;
  }).join('');

  return `<h2>Authors</h2>
<table><thead><tr><th>Author</th><th>Commits</th><th>Added</th><th>Removed</th><th>Active Days</th><th>Share</th></tr></thead>
<tbody>${rows}</tbody></table>`;
}

function languagesSection(languages: LanguageEntry[]): string {
  const rows = languages.map(l => {
    const cls = l.percentage > 60 ? '' : l.percentage > 30 ? 'warn' : '';
    return `<tr>
<td>${escHtml(l.language)}</td>
<td class="num">${l.files}</td>
<td class="num">${l.lines.toLocaleString()}</td>
<td class="num">${l.percentage.toFixed(1)}%</td>
<td><div class="bar-cell"><div class="bar-fill ${cls}" style="width:${l.percentage.toFixed(1)}%"></div></div></td>
</tr>`;
  }).join('');

  return `<h2>Languages</h2>
<table><thead><tr><th>Language</th><th>Files</th><th>Lines</th><th>Share</th><th>Bar</th></tr></thead>
<tbody>${rows}</tbody></table>`;
}

function growthChartScript(points: GrowthPoint[]): { html: string; js: string } {
  const sampled = points.filter((_, i) => i % Math.max(1, Math.floor(points.length / 60)) === 0);
  const labels  = JSON.stringify(sampled.map(p => p.date));
  const data    = JSON.stringify(sampled.map(p => p.totalLines));

  const html = `<div class="chart-wrap"><h3>Repository Growth</h3><canvas id="growthChart" height="80"></canvas></div>`;
  const js   = `new Chart(document.getElementById('growthChart'),{type:'line',data:{labels:${labels},datasets:[{label:'Lines of Code',data:${data},borderColor:'#3fb950',backgroundColor:'rgba(63,185,80,.1)',fill:true,tension:.3,pointRadius:0}]},options:{plugins:{legend:{display:false}},scales:{x:{ticks:{color:'#8b949e',maxTicksLimit:8},grid:{color:'#21262d'}},y:{ticks:{color:'#8b949e'},grid:{color:'#21262d'}}}}});`;

  return { html, js };
}

function patternsChartScript(patterns: CommitPattern): { html: string; js: string } {
  const dayLabels = JSON.stringify(['Sun','Mon','Tue','Wed','Thu','Fri','Sat']);
  const dayData   = JSON.stringify(patterns.daily);
  const hourLabels = JSON.stringify(Array.from({length:24},(_,i)=>String(i)));
  const hourData  = JSON.stringify(patterns.hourly);

  const html = `<div class="grid">
<div class="chart-wrap"><h3>Commits by Day</h3><canvas id="dayChart" height="120"></canvas></div>
<div class="chart-wrap"><h3>Commits by Hour</h3><canvas id="hourChart" height="120"></canvas></div>
</div>`;

  const barCfg = (id: string, labels: string, data: string) =>
    `new Chart(document.getElementById('${id}'),{type:'bar',data:{labels:${labels},datasets:[{data:${data},backgroundColor:'rgba(88,166,255,.7)',borderRadius:3}]},options:{plugins:{legend:{display:false}},scales:{x:{ticks:{color:'#8b949e'},grid:{color:'#21262d'}},y:{ticks:{color:'#8b949e'},grid:{color:'#21262d'}}}}});`;

  const js = barCfg('dayChart', dayLabels, dayData) + barCfg('hourChart', hourLabels, hourData);
  return { html, js };
}

// ---------------------------------------------------------------------------
// Main export
// ---------------------------------------------------------------------------

/**
 * Render the full analytics report as a self-contained HTML file.
 * Uses Chart.js from CDN for interactive charts and inline CSS for a dark theme.
 * @param report - Full analytics report.
 * @returns Complete HTML document string.
 */
export function renderHtmlReport(report: FullReport): string {
  const growth   = growthChartScript(report.growth);
  const patterns = patternsChartScript(report.commitPatterns);

  const body = `
<h1>gitstats — ${escHtml(report.repoName)}</h1>
<p class="meta">Generated ${report.generatedAt.toISOString()}${report.dateRange.since ? ` · since ${report.dateRange.since}` : ''}${report.dateRange.until ? ` · until ${report.dateRange.until}` : ''}</p>
${summaryCards(report)}
<h2>Growth Over Time</h2>
${growth.html}
<h2>Commit Patterns</h2>
${patterns.html}
${authorsSection(report.authors)}
${languagesSection(report.languages)}
`;

  const scripts = growth.js + '\n' + patterns.js;
  return htmlShell(`gitstats — ${report.repoName}`, body, scripts);
}
